@echo off
echo Compilando funciones serverless...
mkdir target\classes 2>nul

echo Compilando DTOs...
javac -encoding UTF-8 -d target/classes src/main/java/com/example/functions/dto/*.java

echo Compilando servicios...
javac -encoding UTF-8 -cp target/classes -d target/classes src/main/java/com/example/functions/service/*.java

echo Compilando funciones...
javac -encoding UTF-8 -cp "target/classes;C:/Program Files/Microsoft/Azure Functions Core Tools/workers/java/lib/*" -d target/classes src/main/java/com/example/functions/*.java src/main/java/com/example/functions/rest/*.java src/main/java/com/example/functions/graphql/*.java

echo Copiando recursos...
xcopy /Y /Q src\main\resources\*.* target\classes\ >nul 2>&1

echo Copiando archivos de configuracion...
copy /Y host.json target\azure-functions\demo-serverless-functions\ >nul 2>&1
copy /Y local.settings.json target\azure-functions\demo-serverless-functions\ >nul 2>&1

echo Iniciando Azure Functions en puerto 7072...
func host start --port 7072